version: "3.9"

services:

  postgres-db:
    image: postgres:15.5-alpine
    container_name: healenium-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: healenium
      POSTGRES_USER: healenium_user
      POSTGRES_PASSWORD: YDk2nmNs4s9aCP6K
    volumes:
      - ./db/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U healenium_user -d healenium"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - healenium

  healenium:
    image: healenium/hlm-backend:3.4.6
    container_name: healenium
    restart: on-failure
    depends_on:
      postgres-db:
        condition: service_healthy
    ports:
      - "7878:7878"
    environment:
      SPRING_POSTGRES_DB: healenium
      SPRING_POSTGRES_SCHEMA: healenium
      SPRING_POSTGRES_USER: healenium_user
      SPRING_POSTGRES_PASSWORD: YDk2nmNs4s9aCP6K
      SPRING_POSTGRES_DB_HOST: postgres-db
      KEY_SELECTOR_URL: "false"
      COLLECT_METRICS: "true"
      HLM_LOG_LEVEL: info
    volumes:
      - ./screenshots:/screenshots
      - ./logs:/logs
    networks:
      - healenium
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7878/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  selector-imitator:
    image: healenium/hlm-selector-imitator:1.4
    container_name: selector-imitator
    restart: on-failure
    ports:
      - "8000:8000"
    networks:
      - healenium

networks:
  healenium:
    name: healenium
